// Auth
export const SET_USER = "SET_USER";
export const CLEAR_USER = "CLEAR_USER";

// Settings
export const SET_SETTING = "SET_SETTING";
export const SET_VIDEO_QUALITY = "SET_VIDEO_QUALITY";
export const SET_CELLULAR_DATA_USAGE_AUTO = "SET_CELLULAR_DATA_USAGE_AUTO";
export const SET_CELLULAR_DATA_USAGE_MODE = "SET_CELLULAR_DATA_USAGE_MODE";
export const RESET_SETTINGS = "RESET_SETTINGS";
